# Generated by Django 5.2.3 on 2025-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buyed_games',
            field=models.ManyToManyField(blank=True, null=True, related_name='buyed_by', to='main.game'),
        ),
    ]
